### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ACTOMtoolbox** [luiscarlosgph/docker-with-graphics#11]
I have followed the instructions, however I am getting an TypeError: 'type' object is not subscriptable message whenever I try to run the examples:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/users/modellers/made/.local/lib/python3.8/site-packages/dockerx/run.py", line 52, in <module>
    def parse_env(list_of_args: list[str]):
TypeError: 'type' object is not subscriptable

I am running a windows machine, connected to a remote ubuntu machine through ssh

**Comment by ACTOMtoolbox** [comment]
This is the command I used:

python3 -m dockerx.run --name wild_turin --image luiscarlosgph/pycharm:latest --nvidia 1 --command /home/docker/pycharm/bin/pycharm.sh

But any of the examples seem to give the same issue

**Comment by luiscarlosgph** [comment]
Hi @ACTOMtoolbox,

Thanks for reporting this issue. Could you please let me know which SSH client you are using in Windows?

Thank you,
Luis.

**Comment by luiscarlosgph** [comment]
Hi @ACTOMtoolbox,

I believe this issue is caused because you are using Python 3.8. Please try Python >= 3.9.

Kind regards,
Luis.
